train_wm:
  wm_batch_size: 16
  sequence_length: 64
  latent_dim: 32
  codes_per_latent: 32
  world_model_learning_rate: 0.0001
  model_dim: 512
  n_transformer_layers: 2
  n_transformer_heads: 2
  dropout: 0.1
  up_projection_factor: 4
  run_eval_episodes: True
  n_eval_episodes: 10
  use_amp: True